name: Check Git Hooks Were Run
run-name: ${{ github.actor }} is checking samples
on: [push]
jobs:
  Sanity-Check-CPP-OpenCL-Sample:
    runs-on: ubuntu-latest
    steps:
      - name: Build Info
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Check GitHooks Run
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-6.0
          git log
          scripts/git_check.sh -c
      - run: echo "ğŸ This job's status is ${{ job.status }}."
