name: Check Python OpenCL Samples
run-name: ${{ github.actor }} is checking samples
on: [push]
jobs:
  Sanity-Check-Python-OpenCL-Sample:
    runs-on: ubuntu-latest
    steps:
      - name: Build Info
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: Check Python OpenCL Sample
        run: |
          pip install pyopencl
          sudo apt install libpocl2 pocl-opencl-icd
          ln -s $PWD TTL
          export TTL_INCLUDE_PATH=$PWD
          export
          cd opencl/samples/python
          ./TTL_sample_runner.py TTL*.cl

      - run: echo "ğŸ This job's status is ${{ job.status }}."
